language: node_js
node_js:
  - "6.7"
  - "5.12"
  - "4.6"
  - "0.12"
  - "0.11"
before_script:
  - npm install -g codecov
script: npm run cov && codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
